# Generated by Django 5.1 on 2024-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='authors/authors_cover')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
