# Generated by Django 5.1 on 2024-08-22 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
