# Generated by Django 5.1 on 2024-08-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='short_description',
        ),
    ]
